### PR TITLE
Replaced comments

### PR DESCRIPTION
**Pull request by szepeviktor**
Please consider uniform comments.

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://github.com/owncloud/core/issues/17781#issuecomment-123316757

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Are you aware of Travis failure in PHP 5.5+?

**Comment by McNetic** [comment]
Yes; that's hindering me from doing a release. It's a problem of getting the travis configuration right; manually running all tests in all sensible configurations does work (afair). Unfortunately, my free time is very limited atm, so if you want to have a look, I'd be very thankful.

**Comment by szepeviktor** [comment]
I am sorry. I also have `There were 2 risky tests`.

**Comment by McNetic** [comment]
I fixed the travis configuration as far as my knowledge allowed, but it still fails for PHP 5.5/5.6. See #24 for the output and follow-up discussion, if you don't mind.

**Comment by McNetic** [comment]
I forgot to ask: I list all contributors in the README.MD file. Do you want to be listed with your name or alias and/or email address?

**Comment by szepeviktor** [comment]
Thank you for your offer.
Please avoid mentioning me.

**Comment by szepeviktor** [comment]
It can be seen here: https://github.com/McNetic/PHPZipStreamer/graphs/contributors

**Comment by McNetic** [comment]
I know. I like to include it in the README for people downloading through other means, e.g. releases and/or packagist. I'm absolutely fine if you don't want to be mentioned.

**Comment by szepeviktor** [comment]
I was here to make your software work for me, not for some kind of glory.

**Comment by McNetic** [comment]
Well, that's my motivation, also. I implemented ZipStreamer to be able to stream files bigger than 700 MB from owncloud without hogging the server ;-).
The contributors list is not about glory, but about copyright. It's still fine and not trying to argue to get you to join.

**Pull request merged**
