### PR TITLE
fixed OSX finder compatibility

### PR DESCRIPTION
**Pull request by jens-maus**
I am by no means a ZIP expert but as this php module is widely using in owncloud I tried to debug why MacOSX is not able to unarchive zip archives generated by ZipStreamer. While the latest sources in the master branch can now be unarchived with the standard OSX 'unzip' command-line tool, unarchiving using the OSX Finder still failed for some reason.

After debugging I found out that it seems to be related to the data descriptor section that ZipStreamer adds to the zip file while the OSX zip unarchiver seems to expect that the file size and compressed size should be stored in the local file header instead. Thus, I modified ZipStreamer accordingly so that no data descriptor is added at all. The code I am requesting to pull here had been tested in my own owncloud installation and it works fine so far. However, apart from not having tested it widely on other platforms it also can be probably widely optimized since now ZipStreamer has to walk through a file twice to first calculate the dataLength, gzLength and crc32 values and then later again to stream the data out.

But it should be good as a first test bed to identify the necessary steps to finally fix OSX compatibility of ZipStreamer and thus also fix OSX compatibility in owncloud.

### CODE REVIEW

**Comment by clementhk** [comment]
Poke :)

**Comment by McNetic** [comment]
Ok; sorry it took so long; but here is the "deflate" branch making use of pecl_http (only version 1, currently). It's no requirement for overall functionality, just if you want to use compression. It fails on Travis for php 5.5 and 5.6, at least for 5.6 due to compatibility problems with pecl_http, but it should work just fine if pecl_http is correctly installed.
I decided I will try to port a simple deflate implementation to php as a fallback to see how it performs, so I will not try to fix the travis builds for now.

**Comment by jens-maus** [comment]
I just got notified about https://github.com/owncloud/core/issues/10001#issuecomment-92502586 and I still feel my pull request here is currently the best alternative to get OS X compatibility for the zip support in owncloud. I know it has some implied performance penalties which can be optimized, but still this solution is way better than simply asking owncloud users to use other unarchiving tools on OSX. I really don't understand why it is so hard to integrate a better zip solution into owncloud? I have my patch here running for a long time now without any issue at all.

**Comment by McNetic** [comment]
Well, I'm sorry it again took so long for me to find time to look into the OSX issue. First, I have to say that this repository is about ZipStreamer, not about Owncloud (strictly speaking), so I will address the owncloud issues in owncloud/core#10001.
Regarding your patch: As I already explained, the goal of ZipStreamer is performance, and working on streams. ZipStreamer does not (and can not) make assumptions about what kind of stream is feeded to addFileFromStream(), and network streams don't support fseek(), so the patch is technically not correct.
Owncloud also only provides a stream from the Filesystem class - I don't know if this stream is always seek()able, as there are different storage backends in owncloud.

**Comment by jens-maus** [comment]
Thanks for the comments. And sorry that I didn't add my comments to https://github.com/owncloud/core/issues/10001, but this issue had been unfortunately closed to comments from collaborators only, so I cannot add anything there anymore.

And of course, I full understand the technical reasons/backgrounds and that ZipStreamer is meant to work on streams only. However, I deeply feel that the owncloud crew itself should then instead use my patched version (after having verified that fseek() works) at least until you have a working streamable version of ZipStreamer that creates OS X-compatible zip files. It is just so frustrating to see that zip support in owncloud is still broken for years now and that there seems to be no end of that story just because of political/minor-technological reasons.

**Comment by McNetic** [comment]
Of course, I also understand your reasoning and frustation. I'm also frustated that I can't solve the problem the way I think is best.
PS: Just for the record: Technically, not the zip support in owncloud is broken, but the zip support in OSX.

**Comment by maennchen** [comment]
We had the same issue in our Zip Utility. We had to change the Zip Version to 0x000A maennchen/ZipStream-PHP#1

http://linlog.skepticats.com/entries/2012/02/Streaming_ZIP_files_in_PHP.php

If the version is changed to that value, UTF-8 Filenames won't work anymore although.

**Comment by McNetic** [comment]
Uhm. No. Setting the needed to extract version to 0x0a does not help with this issue. MacOS might also not like higher version numbers here, but technically, the problem of PHPZipStreamer is not the version field, but the fact that it actually produces streamed zip files as of the zip standard, setting general purpose bit 3 (ADD), setting size/crc in the local file headers to 0, and append them in data descriptors (and the central directory). All other zip "stream" implementations i found don't do that (and neither does yours). The problem is, my implementation does (and by design, can only) do one pass over each "file", as it works purely on streams with potentially no fseek() available (it's also about speed with big files). The problem itself was also discussed in #16.

**Comment by cthil** [comment]
A short addendum: The Zip file issue is not limited to OS X, but also the default KDE archiver Ark (Version 2.19, Debian 8, libz.so.1.2.8) cannot extract the file. It presents the top-level directory followed by an error message. CLI unzip v.6 is fine.

**Comment by McNetic** [comment]
I think there will be no news insights to the problem, and the workarounds are now well known and/or in place, so I think I can close this one.

**Pull request closed without merging**
