### PR TITLE
Fix zip generation for 7zip

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Fix issue #37

### CODE REVIEW

**Comment by glannes31** [comment]
Any update ??? We have the problem in owncloud 10.0.3  .

**Comment by DeepDiver1975** [comment]
> Any update ??? We have the problem in owncloud 10.0.3 .

10.0.4 already fixes this issue - please upgrade

**Comment by LorbusChris** [comment]
Any chance this is getting merged soon?

**Comment by DeepDiver1975** [comment]
> Any chance this is getting merged soon?

I consider this repo dead - feel free to grab the changes from my fork.

**Comment by LorbusChris** [comment]
Ok, thank you for the info. I will resort to bundling the vendored/patched version of it with NC :)

In the longer run I reckon there should either be a maintained fork of this or OC/NC should drop the dependency.

**Comment by DeepDiver1975** [comment]
> Ok, thank you for the info. I will resort to bundling the vendored/patched version of it with NC :)
> 
> In the longer run I reckon there should either be a maintained fork of this or OC/NC should drop the dependency.

FYI roland just started contributing to the my fork as well. as long as nobody cries - we can continue this way

**Comment by DeepDiver1975** [comment]
> Ok, thank you for the info. I will resort to bundling the vendored/patched version of it with NC :)

grab it from https://packagist.org/packages/deepdiver/zipstreamer

**Comment by LorbusChris** [comment]
Does this fork contain all changes required for NC? If you don't mind I will create an rpm package of your fork for Fedora, so I don't have to bundle it.

**Comment by DeepDiver1975** [comment]
> Does this fork contain all changes required for NC?

no idea - you need to talk with the nc guys



> If you don't mind I will create an rpm package of your fork for Fedora, so I don't have to bundle it.

No issues with this - THX

**Comment by DeepDiver1975** [comment]
I consider this repo dead ... feel free to use my fork

**Pull request closed without merging**
