### PR TITLE
Add resume and content-length to ZipStreamer

### PR DESCRIPTION
**Pull request by rfnx**
- Add resume function
- Give content-length before streaming
- Fix zip structure
- Cleaning
- Count64 class replaced by floats to simplify the comparison operations (no issue for file size less than approximately 2^50 B, see https://github.com/fruux/sabre-dav/issues/408)

I also removed addEmptyDir function, because it was never useful in any zip software I tested : 
- Winzip (Windows)
- Winrar (Windows)
- Windows explorer (Windows)
- PeaZip (Windows)
- A CSharp zip archiver (Windows)
- The Expander (Mac OS X)
- Unarchiver (Mac OS X)
- unzip (Linux)

I had no error for any of these softs : zip structure is OK even if the zip was created on a 32bit platform with file size greater than 8GB.

PS : this PR has to be merged simultaneously with https://github.com/owncloud/core/pull/7942 to work correctly

### CODE REVIEW

**Comment by McNetic** [comment]
As there is no activity here for quite some time, some (if not so say most relevant) issues adressed here have already been solved, and the basic goal does not comply with the goal of ZipStreamer, I close this pull request.
If you think some part of your contribution should still be included in ZipStreamer, feel free to comment here and/or create a new (if possible smaller and more atomic) pull request(s). But please, be aware that ZipStreamer will always stay with the assumption to work on input streams with no fseek() available.

**Comment by rfnx** [comment]
ownCloud has so many issues and regressions it's really not important anymore haha.

**Comment by LukasReschke** [comment]
>ownCloud has so many issues and regressions it's really not important anymore haha.

FUD. https://owncloud.org/blog/owncloud-grows-to-8-million-users/

**Comment by rfnx** [comment]
I said nothing about popularity. I just think 8.2 has regressions, I hope 9 will be better.

**Pull request closed without merging**
